//!User
export const DASHBOARD_SET_USERNAME_START = "DASHBOARD_SET_USERNAME_START";
export const DASHBOARD_SET_USERNAME_SUCCESS = "DASHBOARD_SET_USERNAME_SUCCESS";
export const DASHBOARD_SET_USERNAME_FAIL = "DASHBOARD_SET_USERNAME_FAIL";

export const DASHBOARD_SET_ACTIVE_USERS_START =
  "DASHBOARD_SET_ACTIVE_USERS_START";
export const DASHBOARD_SET_ACTIVE_USERS_SUCCESS =
  "DASHBOARD_SET_ACTIVE_USERS_SUCCESS";
export const DASHBOARD_SET_ACTIVE_USERS_FAIL =
  "DASHBOARD_SET_ACTIVE_USERS_FAIL";

export const DASHBOARD_SET_GROUP_CALL_ROOMS_START =
  "DASHBOARD_SET_GROUP_CALL_ROOMS_START";
export const DASHBOARD_SET_GROUP_CALL_ROOMS_SUCCESS =
  "DASHBOARD_SET_GROUP_CALL_ROOMS_SUCCESS";
export const DASHBOARD_SET_GROUP_CALL_ROOMS_FAIL =
  "DASHBOARD_SET_GROUP_CALL_ROOMS_FAIL";

export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";

//!Call RTC
export const CALL_SET_LOCAL_STREAM_START = "CALL_SET_LOCAL_STREAM_START";
export const CALL_SET_LOCAL_STREAM_SUCCESS = "CALL_SET_LOCAL_STREAM_SUCCESS";
export const CALL_SET_LOCAL_STREAM_FAIL = "CALL_SET_LOCAL_STREAM_FAIL";

export const CALL_SET_CALL_STATE_START = "CALL_SET_CALL_STATE_START";
export const CALL_SET_CALL_STATE_SUCCESS = "CALL_SET_CALL_STATE_SUCCESS";
export const CALL_SET_CALL_STATE_FAIL = "CALL_SET_CALL_STATE_FAIL";

export const CALL_SET_CALLING_DIALOG_VISIBLE_START =
  "CALL_SET_CALLING_DIALOG_VISIBLE_START";
export const CALL_SET_CALLING_DIALOG_VISIBLE_SUCCESS =
  "CALL_SET_CALLING_DIALOG_VISIBLE_SUCCESS";
export const CALL_SET_CALLING_DIALOG_VISIBLE_FAIL =
  "CALL_SET_CALLING_DIALOG_VISIBLE_FAIL";

export const CALL_SET_CALLER_USERNAME_START = "CALL_SET_CALLER_USERNAME_START";
export const CALL_SET_CALLER_USERNAME_SUCCESS =
  "CALL_SET_CALLER_USERNAME_SUCCESS";
export const CALL_SET_CALLER_USERNAME_FAIL = "CALL_SET_CALLER_USERNAME_FAIL";

export const CALL_SET_CALL_REJECTED_START = "CALL_SET_CALL_REJECTED_START";
export const CALL_SET_CALL_REJECTED_SUCCESS = "CALL_SET_CALL_REJECTED_SUCCESS";
export const CALL_SET_CALL_REJECTED_FAIL = "CALL_SET_CALL_REJECTED_FAIL";

export const CALL_SET_REMOTE_STREAM_START = "CALL_SET_REMOTE_STREAM_START";
export const CALL_SET_REMOTE_STREAM_SUCCESS = "CALL_SET_REMOTE_STREAM_SUCCESS";
export const CALL_SET_REMOTE_STREAM_FAIL = "CALL_SET_REMOTE_STREAM_FAIL";

export const CALL_SET_LOCAL_MICROPHONE_ENABLED_START =
  "CALL_SET_LOCAL_MICROPHONE_ENABLED_START";
export const CALL_SET_LOCAL_MICROPHONE_ENABLED_SUCCESS =
  "CALL_SET_LOCAL_MICROPHONE_ENABLED_SUCCESS";
export const CALL_SET_LOCAL_MICROPHONE_ENABLED_FAIL =
  "CALL_SET_LOCAL_MICROPHONE_ENABLED_FAIL";

export const CALL_SET_LOCAL_CAMERA_ENABLED_START =
  "CALL_SET_LOCAL_CAMERA_ENABLED_START";
export const CALL_SET_LOCAL_CAMERA_ENABLED_SUCCESS =
  "CALL_SET_LOCAL_CAMERA_ENABLED_SUCCESS";
export const CALL_SET_LOCAL_CAMERA_ENABLED_FAIL =
  "CALL_SET_LOCAL_CAMERA_ENABLED_FAIL";

export const CALL_SET_SCREEN_SHARING_ACTIVE_START =
  "CALL_SET_SCREEN_SHARING_ACTIVE_START";
export const CALL_SET_SCREEN_SHARING_ACTIVE_SUCCESS =
  "CALL_SET_SCREEN_SHARING_ACTIVE_SUCCESS";
export const CALL_SET_SCREEN_SHARING_ACTIVE_FAIL =
  "CALL_SET_SCREEN_SHARING_ACTIVE_FAIL";

export const CALL_RESET_CALL_STATE_START = "CALL_RESET_CALL_STATE_START";
export const CALL_RESET_CALL_STATE_SUCCESS = "CALL_RESET_CALL_STATE_SUCCESS";
export const CALL_RESET_CALL_STATE_FAIL = "CALL_RESET_CALL_STATE_FAIL";

export const CALL_SET_GROUP_CALL_ACTIVE_START =
  "CALL_SET_GROUP_CALL_ACTIVE_START";
export const CALL_SET_GROUP_CALL_ACTIVE_SUCCESS =
  "CALL_SET_GROUP_CALL_ACTIVE_SUCCESS";
export const CALL_SET_GROUP_CALL_ACTIVE_FAIL =
  "CALL_SET_GROUP_CALL_ACTIVE_FAIL";

export const CALL_SET_GROUP_CALL_STREAMS_START =
  "CALL_SET_GROUP_CALL_STREAMS_START";
export const CALL_SET_GROUP_CALL_STREAMS_SUCCESS =
  "CALL_SET_GROUP_CALL_STREAMS_SUCCESS";
export const CALL_SET_GROUP_CALL_STREAMS_FAIL =
  "CALL_SET_GROUP_CALL_STREAMS_FAIL";

export const CALL_CLEAR_GROUP_CALL_DATA_START =
  "CALL_CLEAR_GROUP_CALL_DATA_START";
export const CALL_CLEAR_GROUP_CALL_DATA_SUCCESS =
  "CALL_CLEAR_GROUP_CALL_DATA_SUCCESS";
export const CALL_CLEAR_GROUP_CALL_DATA_FAIL =
  "CALL_CLEAR_GROUP_CALL_DATA_FAIL";

export const CALL_SET_CHAT_MESSAGE_START = "CALL_SET_CHAT_MESSAGE_START";
export const CALL_SET_CHAT_MESSAGE_SUCCESS = "CALL_SET_CHAT_MESSAGE_SUCCESS";
export const CALL_SET_CHAT_MESSAGE_FAIL = "CALL_SET_CHAT_MESSAGE_FAIL";
